### ISSUE TITLE
KwArgs with multiple `-map` arguments

### ISSUE THREAD

**Issue by ljrk0** [u2takey/ffmpeg-go#1]
Hi, great library!

I'm trying to figure out how/whether multiple `-map` arguments are supported.  E.g., in order to add artwork to a file, I'd do

    ffmpeg -i "input_file.mp4" -i "Input_file.jpg" --map 1 -map 0  -acodec copy -vcodec copy "output_file.mp4"

(source: https://stackoverflow.com/a/53950948/4453524).  However, KwArgs obviously complains that I use the `-map` key twice.  Is there something I'm overlooking?

**Comment by u2takey** [comment]
check ffmpeg_test.go, will TestCombinedOutput help?

```
func TestCombinedOutput(t *testing.T) {
	i1 := Input(TestInputFile1)
	i2 := Input(TestOverlayFile)
	out := Output([]*Stream{i1, i2}, TestOutputFile1)
	assert.Equal(t, []string{
		"-i",
		TestInputFile1,
		"-i",
		TestOverlayFile,
		"-map",
		"0",
		"-map",
		"1",
		TestOutputFile1,
	}, out.GetArgs())
}

```

**Comment by ljrk0** [comment]
Yes, thank you -- I totally missed that.

---

FWIW, I'm toying around a bit by trying to implement some of the functionality of the horrible [1] bash-script https://github.com/KrumpetPirate/AAXtoMP3 at to Go: https://codeberg.org/ljrk/go-aax, while trying to learn a bit about the language, hence my interest in this library!

[1]: Horrible because it mixes POSIX test `[ ... ]` with bashisms like `[[ ... ]]` and uses `[[ $(($bar > 10)) == "1" ]]` instead of `[ "$bar" -ge 10 ]`, etc.

**Comment by elboletaire** [comment]
Hey @u2takey, doing what's done in that example, what I'm getting is some maps appended to the args string, but I need to specify the maps of my own. This is the command I'm trying to replicate:

~~~bash
ffmpeg -i input-file -c:a copy -c:v libx264 -crf 18 -map 0:v:0 -map 0:m:language:cat output-file
~~~

But doing what's done in that example, this is the most nearby command I've got:

~~~bash
ffmpeg -i input-file -map 0:a -map 0:v -c copy -c:v libx264 -crf 18 -map 0:m:language:cat output-file
~~~

The additional `-map 0:a` at the beginning makes ffmpeg completely ignore the next `-map` I'm setting when trying to output it.

Is there any workaround for this?

**Comment by warmans** [comment]
This is still a problem IMO. I ended up having to fork the repo to make it work for my usecase: https://github.com/warmans/ffmpeg-go

It's not that easy to fix properly. Arguably the arguments just shouldn't be maps since some can be supplied more than once. In this case I just implemented a workaround by allowing map arguments with a unique suffix i.e. `map_0`, `map_1` then transform these into normal `-map` args when it builds the command 🤷 

edit: I realised this collides with some existing param and changed it to `_map_0` (added underscore prefix).

**Comment by memoryonrepeat** [comment]
@warmans Thanks a lot, I was dealing with the same problem and your fork works perfectly 🚀

**Comment by lapinn-a** [comment]
If anyone was looking for a solution and nothing helps, this code works for me:

```go
err = ffmpeg.Input(tmpFilePath).Output(
	path.Join(livePath, outputFileName),
	ffmpeg.KwArgs{"acodec": "copy", "vcodec": "copy"},
	ffmpeg.KwArgs{"map": []string{"0:v:0", "0:v:1", "0:v:2", "0:a:0", "0:a:0", "0:a:0"}},
	ffmpeg.KwArgs{"var_stream_map": "v:0,a:0,name:high v:1,a:1,name:mid v:2,a:2,name:low"},
	ffmpeg.KwArgs{"hls_list_size": 0, "f": "hls"},
).
OverWriteOutput().Run()
```
