### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by JamesTiberiusKirk** [u2takey/ffmpeg-go#10]
Hi quick question. In a very specific env I keep getting exit status 1 and I have no idea how to go about troubleshooting this.

For context: 
docker image with alpine linux on my arch linux development machine works fine
same docker image on a digital ocean vps returns exit status one from ffmpeg

**Comment by u2takey** [comment]
it's true problem that ffmpeg-go do not print enough error detail for troubleshooting. I will do some work to optimize that. For now, you can just use method `GetArgs()` which print all args generated for command ffmpeg, and run command ffmpeg manually with these args, do this will get you more information about the failure.

**Comment by JamesTiberiusKirk** [comment]
Right I see, thanks!

**Comment by u2takey** [comment]
In this pr: https://github.com/u2takey/ffmpeg-go/pull/12, an option: `ErrorToStdOut`, `WithErrorOutput` and  is imported, with which error output from FFmpeg will be ouputed to stdout or a `writer`
