### ISSUE TITLE
enhance opencv example 

### ISSUE THREAD

**Issue by fastfading** [u2takey/ffmpeg-go#13]
what if  I need to do 
ffmpeg capture camera -> opencv image process -> ffmpeg to file or stream

what would be the code look like with this lib.

**Comment by u2takey** [comment]
> what if I need to do
> ffmpeg capture camera -> opencv image process -> ffmpeg to file or stream
> 
> what would be the code look like with this lib.

please refer examples in examples/opencv_test.go, uncomment `+build gocv` before you try to run these two examples.
