### ISSUE TITLE
How to use MergeKwArgs

### ISSUE THREAD

**Issue by jw-star** [u2takey/ffmpeg-go#22]
```
args := ffmpeg.KwArgs{"c:v": "libx264", "threads": "2"}
	if videoLen > 240 {
		args = ffmpeg.KwArgs{"c:v": "libx264",  "threads": "2" ,"ss": "00:00:10"}
		ffmpeg.MergeKwArgs(???????)
	}
```

**Comment by wolveix** [comment]
In your example, there's no need to merge `ffmpeg.KwArgs` as you're basically redeclaring it in the second instance. But for your reference, `ffmpeg.MergeKwArgs` can be used like this:

```golang
args0 := ffmpeg.KwArgs{"c:v": "libx264"}
args1 := ffmpeg.KwArgs{"threads": "2"}

args := ffmpeg.MergeKwArgs([]ffmpeg.KwArgs{
	args0,
	args1,
})
```

**Comment by jw-star** [comment]
> In your example, there's no need to merge `ffmpeg.KwArgs` as you're basically redeclaring it in the second instance. But for your reference, `ffmpeg.MergeKwArgs` can be used like this:
> 
> ```go
> args0 := ffmpeg.KwArgs{"c:v": "libx264"}
> args1 := ffmpeg.KwArgs{"threads": "2"}
> 
> args := ffmpeg.MergeKwArgs([]ffmpeg.KwArgs{
> 	args0,
> 	args1,
> })
> ```

Thank you very much for your example, I learned！！！
