### ISSUE TITLE
multiple inputs

### ISSUE THREAD

**Issue by sdinkova** [u2takey/ffmpeg-go#24]
I need to to have two inputs in order to manipulate audio and video as shown in the first example here https://newbedev.com/adding-silent-audio-in-ffmpeg . Right now there is only one input per ffmpeg command. Could this be added?

**Comment by u2takey** [comment]
you could refer to https://github.com/u2takey/ffmpeg-go/blob/master/ffmpeg_test.go#L87, use []*ffmpeg.Stream{input1, input2}, as param for output function.
