### ISSUE TITLE
Pls,need Help! How to merge video clip?

### ISSUE THREAD

**Issue by PageNotFound200** [u2takey/ffmpeg-go#35]
i want to merger some video clip which like "a.mp4", "b.mp4" , But i don't know how to use ffmpeg-go to merge them, ( on command line i use ffmpeg -i "concat:a.mp4|b.mp4" -c copy output10.mp4)
How to merge video clip?
Can u offer some demo , thanks!
Pls,need Help!

**Comment by u2takey** [comment]
> i want to merger some video clip which like "a.mp4", "b.mp4" , But i don't know how to use ffmpeg-go to merge them, ( on command line i use ffmpeg -i "concat:a.mp4|b.mp4" -c copy output10.mp4) How to merge video clip? Can u offer some demo , thanks! Pls,need Help!

try:
```
in1, in2 := ffmpeg.Input("./in1.mp4"), ffmpeg.Input("./in2.mp4")
cmd := ffmpeg.Concat([]*ffmpeg.Stream{in1, in2}).Output("./concat.mp4")
cmd.OverWriteOutput().ErrorToStdOut().Run()
```

**Comment by PageNotFound200** [comment]
Thanks,
