### ISSUE TITLE
CPU limits and RunWithResource

### ISSUE THREAD

**Issue by dedo1911** [u2takey/ffmpeg-go#37]
In README there's a whole section dedicated to **Set Cpu limit/request For FFmpeg-go**,
but RunWithResource is not available in the code.

What is that function and how to use it?

**Comment by u2takey** [comment]
> In README there's a whole section dedicated to **Set Cpu limit/request For FFmpeg-go**, but RunWithResource is not available in the code.
> 
> What is that function and how to use it?

missing method, fixed in https://github.com/u2takey/ffmpeg-go/pull/38; it is only  available on linux.
