### ISSUE TITLE
Stdin pipe not working

### ISSUE THREAD

**Issue by gabivlj** [u2takey/ffmpeg-go#54]
Hi! When you try to use an `io.Reader` input and specify 'pipe:' like this:

```go
	fd, err := os.Open("./file.mp3")
	if err != nil {
		panic(err)
	}
	err = ffmpeg_go.Input("pipe:", ffmpeg_go.KwArgs{"format": "mp3"}).
		WithInput(fd).
		Output("./playlist.m3u8", ffmpeg_go.KwArgs{"c:a": "aac", "b:a": "320k", "hls_list_size": "0", "hls_time": "20"}).
		OverWriteOutput().ErrorToStdOut().Run()
```

It doesn't work as expected:
![image](https://user-images.githubusercontent.com/24482526/172467824-37966156-dc5d-4e9c-9d06-cbdb66f69607.png)

If you try to do the compiled command with a pipe
```
cat file.mp3 | ffmpeg -f mp3 -i pipe: -b:a 320k -c:a aac -hls_list_size 0 -hls_time 20 ./playlist.m3u8 -y
```

It should work.

As I can see, the library  uses the 'Stdin' key on the context to save the `io.Reader`, but when it calls `Output()` it creates an output node, then calls `Stream()`,  which is initialised with `context.Background()` as seen here:

https://github.com/u2takey/ffmpeg-go/blob/8af5c3849807dcda756406a7b2b3631a5c90d53b/node.go#L28-L36
This makes the previous keys like 'Stdin' to not exist anymore.

One solution would be setting somewhere the previous stream context to the next stream that output returns.
Maybe by doing it here?
https://github.com/u2takey/ffmpeg-go/blob/8af5c3849807dcda756406a7b2b3631a5c90d53b/ffmpeg.go#L81-L91

It happens on github.com/u2takey/ffmpeg-go v0.4.1

**Comment by OGreeni** [comment]
Any update? Facing the same issue...

**Comment by gabivlj** [comment]
I have this PR:
https://github.com/u2takey/ffmpeg-go/pull/90

But you can also use this fork that I created with the fix:
https://github.com/gabivlj/ffmpeg-go

If you see any issues lmk.

**Comment by gabivlj** [comment]
https://github.com/u2takey/ffmpeg-go/pull/90 closing
