### ISSUE TITLE
Concatenating more than 10 streams results in streams out of order

### ISSUE THREAD

**Issue by zainhoda** [u2takey/ffmpeg-go#58]
The labels are lexically sorted so the conversion from int to string should contain a left pad otherwise when the labels get sorted, it goes 0, 1, 10, 11, 12, ... , 2, 3, 4, ... :

https://github.com/u2takey/ffmpeg-go/blob/8af5c3849807dcda756406a7b2b3631a5c90d53b/node.go#L204

I would recommend changing this from `%v` to `%02d`

**Comment by mikeford** [comment]
@zainhoda I also just hit this bug. +1 for fixing this, but perhaps the solution should determine the padding based on the number of files in the directory instead of hardcoding 2,3,4 etc digits.
