### ISSUE TITLE
Generated ffmpeg command is wrong!

### ISSUE THREAD

**Issue by tahacodes** [u2takey/ffmpeg-go#70]
Hi and thanks for this great go package.

I tried to run this block of code:

```
func TakeScreenshot(filePath string, destination string, timestamp int) error {
	err := ffmpeg.
		Input(filePath).
		OverWriteOutput().
		Output(destination).
		GlobalArgs("-y", "-ss 1", "-vframes 1", "-q:v 2", "-vf", "scale=1080:-1").
		Run()

	if err != nil {
		return err
	}

	return nil
}
```

And from the stdout of my code i saw that it was trying to run this command:
`ffmpeg -i ./tmp/file.mp4 ./tmp/screenshot.jpg -y -ss 1 -vframes 1 -q:v 2 -vf scale=1080:-1`

Which happened to not work at all, the correct command for creating a thumbnail is this one:
`ffmpeg -i ./tmp/file.mp4 -y -ss 1 -vframes 1 -q:v 2 -vf scale=1080:-1 ./tmp/screenshot.jpg`

Simply the position of the output file should not be in the middle. Am i doing something wrong here?

**Comment by Mnib** [comment]
Hi,
I'm probably answering this a bit late, but that would be something like:

```go
if err := ffmpeg_go.
    Input(file_name, ffmpeg_go.KwArgs{
	"ss": "1",
    }).
    Output(output_path, ffmpeg_go.KwArgs{
	"frames:v": "1",
	"q:v":      "2",
	"vf":       "scale=1080:-1",
    }).
    Run(); err != nil {
    return err
}
```

Or something along those lines.

Hope this helps

**Comment by tahacodes** [comment]
Thanks mate, it works just fine.
