### ISSUE TITLE
Could we have a new release to include the `Silent()` function?

### ISSUE THREAD

**Issue by NoraWang12** [u2takey/ffmpeg-go#95]
Hi @u2takey, I wonder if the `ffmpeg-go` could have a new release for the package to include the `Silent()` function to suppress the log for the `ffmpeg` command? The PR has been merged: https://github.com/u2takey/ffmpeg-go/pull/81. Thank you!

**Comment by NikoGrano** [comment]
@NoraWang12 This is already shipped, so could you close this ticket as the maintainers did not do it. 👍
